merging in this monster rolling pr
* WIP

* Removed specific thing

* added some google scholar stuff

* WIP commit

* WIP checkpoint

* WIP commit

* scribus stub: added a little more

* Deps: bumped py libs dep

* Work on calendar craps

* WIP

* Removed specific thing

* added some google scholar stuff

* WIP commit

* WIP checkpoint

* WIP commit

* Work on calendar craps

* bit of plussing

* Taskfile: added alias

* blacked stupbs

* stubs

* Stubs: Improved stubs

* some stub wip

* cleanup

* more wip

* plussed code

* added some source test files

* added some stuff i guess

* linted

* WIP

* draw page eh

* more wip

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -1,28 +1,145 @@
 version: "3"
+
+includes:
+  scribus:
+    taskfile: "task/scribus/Taskfile.yml"
+
+
+  py-cache:
+    # This is what I would use for another repo:
+    # taskfile: 'https://raw.githubusercontent.com/pretty-weed/toolbelt/refs/heads/main/task/cache_python_deps/Taskfile.yml'
+    taskfile: 'task/cache_python_deps/Taskfile.yml'
+    vars:
+      WHEEL_CACHE: '{{ .WHEEL_CACHE | default "local" }}'
+
 vars:
+  CURRENT_OS_REPO:
+    sh: lsb_release --id --short || echo "ubuntu"
+  CURRENT_TAG:
+    sh: lsb_release --release --short || echo "latest"
+  ALL_EXTRAS:
+    sh: python3 -c "import tomllib, pathlib;print(','.join(tomllib.loads(pathlib.Path('pyproject.toml').read_text()).get('project', {}).get('optional-dependencies', {}).keys()))"
+  EXTRAS:
+    ref: splitList "," .ALL_EXTRAS
+  CACHED_INSTALL_FLAGS: '--find-links=file:{{ .CACHE_DIR }} {{ if .OFFLINE }}--no-index{{ end }}'
+  OFFLINE: '{{ .OFFLINE | default "" }}'
+  DOCKER_TAG_REPO: '{{ .CONTAINER_TAG | default "dd-toolbelt" }}'
+  CONTAINER_WORKING_COPY_DIR: /tmp/working_copy
+
   DEFAULT_BIN_DIR:
     sh: |
       bin_path=""
       for test_path in $(echo $PATH | tr ":" "\n"); do
-      [[ "${test_path}" == $HOME/*bin ]] && bin_path="${test_path}" 
+      [[ "${test_path}" == $HOME/*bin ]] && bin_path="${test_path}" || :
       done
-      test -n "${bin_path}" && echo "${bin_path}"
+      test -n "${bin_path}" && echo "${bin_path}"F
+
+  TOOLBELT_TASK_REF: '{{ .TOOLBELT_TASK_REF | default "main"}}'
+  TOOLBELT_TASK_PATH: '{{ .TOOLBELT_TASK_PATH | default "task"}}'
+
 tasks:
+  cache-deps-example:
+    run: once
+    help: example of how to do this.
+    includes:
+      this-but-remote: https://raw.githubusercontent.com/pretty-weed/toolbelt/{{ .TOOLBELT_TASK_REF }}{{ .TOOLBELT_TASK_PATH}}/Taskfile.yml
+
+
   scribus-install:
     interactive: true
     cmds:
-      - sudo find /usr/share/scribus/scripts/dandi* -name __pycache__ -exec rm -rf {} \; || true
-      - sudo rm -rf /usr/share/scribus/scripts/__pycache__
-      - sudo /usr/bin/python3 -m pip install '.' --upgrade --target '/usr/share/scribus/scripts/'
-      - sudo rm -rf ./build
-    
+      - for: ["LOCAL", "USER", "GLOBAL", ".my-cool-cache"]
+        task: py-cache:default
+        vars:
+          CACHE_DIR: '{{ .ITEM }}'
+        cmd: 'echo {{ .py_cache.CACHE_DIR}} or {{ .CACHE_DIR}}'
+      - echo {{ .ALL_EXTRAS }}
+      - echo {{ .EXTRAS }}
+
   clean-scribus-pycache:
+    vars:
+      INSTALL_BASE:
+        sh: "pip show -f danditools | grep '^Location' | sed 's;Location: ;;'"
+
+    cmds:
+      - task: scribus:clean-pycache
+        vars:
+          INSTALL_BASE: '{{ .INSTALL_BASE }}'
+
+
+  build-test-container:
+    aliases: ["build-container"]
+    dir: '{{ .ROOT_DIR }}'
+    vars:
+      TAG: '{{ .TAG | default .DOCKER_TAG_REPO }}'
+      FROM_REPO: '{{ .FROM_REPO | default .CURRENT_OS_REPO | lower }}'
+      FROM_TAG: '{{ .FROM_TAG | default .CURRENT_TAG | lower }}'
+    sources:
+      - docker/testme/**
+    cmds:
+      - >
+        docker buildx build . --file docker/testme/Dockerfile
+        --build-arg "BASE_REPO={{ .FROM_REPO }}"
+        --build-arg "BASE_VERSION={{ .FROM_TAG }}"
+        --build-arg "WORKING_COPY_DIR={{ .CONTAINER_WORKING_COPY_DIR }}"
+        --tag {{ .TAG }}:latest {{ .CLI_ARGS }}
+
+  in-container:
     interactive: true
-    cmds: 
-      - | 
-        for fname in $(find /usr/share/scribus/scripts/ -name __pycache__); do
-        test -e $fname && sudo rm -rf $fname
-        done
+    deps:
+      - build-test-container
+    vars:
+      TAG: '{{ .TAG | default (printf "%s:latest" .DOCKER_TAG_REPO) }}'
+
+    cmds:
+      - docker run -it -v "$(pwd):{{ .CONTAINER_WORKING_COPY_DIR }}"  {{ .TAG }}
+
+
+  cache-deps:
+    preconditions:
+      - cmd: exit 12
+        msg: "importlib_metadata must be installed in the current python env"
+    vars:
+      BUILD_DEPS: "setuptools setuptools-scm wheel"
+
+    cmds:
+      - for: ["", "[profile]"]
+        task: py-cache:cache_deps
+        vars:
+          PACKAGES: '{{ .ROOT_DIR }}{{ .ITEM }} {{ .BUILD_DEPS }}'
+
+  install:
+    aliases: ["I"]
+    vars:
+      PACKAGE: '.'
+    preconditions:
+      # I would do this with requires:{vars:{name: enum:}} but that doesn't support a ref it seems
+      - cmd: ":" # TODO, fail if package is not a valid EXTRA
+    cmds:
+      # always do an editable install, as that caches the github dep
+      # ToDo: Make editable optional
+      - 'pip install {{ .CACHED_INSTALL_FLAGS }} -e {{ .PACKAGE }}'
+
+  install-offline:
+    # ToDo: handle github with cached
+    aliases: ["offline-install", "Io"]
+    cmds:
+      - task: install
+        vars: {"OFFLINE": "darnTootin"}
+
+  install-brute:
+    aliases: ["brute-install", "Ib"]
+    cmds:
+      - 'pip wheel {{ .CACHED_INSTALL_FLAGS }} --no-deps {{ .ROOT_DIR}}'
+
+  generate-stubs:
+    aliases:
+      - stubs
+    vars:
+      STUB_DIR: type_stubs
+    cmds:
+      - stubgen --package danditools --package dandiscribe --output {{ .STUB_DIR }} {{ .CLI_ARGS }}
+      - black {{ .STUB_DIR }}
 
   install-shell-scripts:
     aliases:
